version: '3'

services:
  openhim-mongo:
    container_name: openhim-mongo
    image: mongo:4.2
    ports:
      - "27017:27017"
    
  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:v7.0.2
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    depends_on:
      - mongo
  
  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:v1.14.3
    ports:
        - "9000:80"
    volumes:
      - ./default.json:/usr/share/nginx/html/config/default.json
    
